### ISSUE TITLE
Requirements.txt not installing required libraries on Windows.

### ISSUE THREAD

**Issue by nickywojcik** [nickywojcik/CMSC495TEAM5#17]
After running the pip install -r requirements.txt command, the following libraries still do not install:

flask
torchvision
torch
Pillow

These libraries need to be installed individually through pip.

**Comment by jackboswell** [comment]
Removed nvidia module requirements.  These modules are still required on CentOS, but the installation of Flask by itself will call the nvidia dependences.

Linked branch contains updated requirements files that works on both Windows and Linux for me.  I need someone to test this as well.  Recommend switching to the linked branch, do a git pull, create a new virtual environment, install requirements.txt using pip -r, and running the integration test and the flask server.

Note: Sometimes the integration fails because the model mistakes a golden retriever for a norfolk terrier (which do not look that much alike).  After a few runs, it seems to get better.

**Comment by nickywojcik** [comment]
I can confirm that after clearing my libraries (uninstalling all pip modules and clearing caches) the new requirements.txt succeeds in installing all required packages. I will merge the branch with the main branch and mark the issue as closed.
